# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core_ingest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/core_ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/core_ingest.proto\x12\x04\x63ore\"\xf3\x01\n\x06Metric\x12\x17\n\x0f\x64\x65vice_hostname\x18\x01 \x01(\t\x12\x35\n\rmetric_values\x18\x02 \x03(\x0b\x32\x1e.core.Metric.MetricValuesEntry\x12$\n\x04tags\x18\x03 \x03(\x0b\x32\x16.core.Metric.TagsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x1a\x33\n\x11MetricValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t23\n\nCoreIngest\x12%\n\nSendMetric\x12\x0c.core.Metric\x1a\t.core.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.core_ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC_METRICVALUESENTRY']._loaded_options = None
  _globals['_METRIC_METRICVALUESENTRY']._serialized_options = b'8\001'
  _globals['_METRIC_TAGSENTRY']._loaded_options = None
  _globals['_METRIC_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_METRIC']._serialized_start=34
  _globals['_METRIC']._serialized_end=277
  _globals['_METRIC_METRICVALUESENTRY']._serialized_start=181
  _globals['_METRIC_METRICVALUESENTRY']._serialized_end=232
  _globals['_METRIC_TAGSENTRY']._serialized_start=234
  _globals['_METRIC_TAGSENTRY']._serialized_end=277
  _globals['_ACK']._serialized_start=279
  _globals['_ACK']._serialized_end=318
  _globals['_COREINGEST']._serialized_start=320
  _globals['_COREINGEST']._serialized_end=371
# @@protoc_insertion_point(module_scope)
