# snmpd.conf — mimics MikroTik CRS Switch
agentAddress  udp:161
rocommunity   public default

# 1.3.6.1.4.1.14988 → matches "mikrotik" + "router" (MikroTik uses same enterprise OID)
sysObjectID   1.3.6.1.4.1.14988.1

sysDescr      RouterOS CRS326-24G-2S+RM (MIPSBE) version 6.49.6 (stable) — SwOS/RouterOS Switch
sysName       MikroTik-Switch-SIM
sysContact    admin@company.com
sysLocation   DataCenter-Rack-C2