# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import core_ingest_pb2 as core__ingest__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreIngestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMetric = channel.unary_unary(
                '/core.CoreIngest/SendMetric',
                request_serializer=core__ingest__pb2.Metric.SerializeToString,
                response_deserializer=core__ingest__pb2.Ack.FromString,
                _registered_method=True)


class CoreIngestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetric,
                    request_deserializer=core__ingest__pb2.Metric.FromString,
                    response_serializer=core__ingest__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.CoreIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.CoreIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreIngest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.CoreIngest/SendMetric',
            core__ingest__pb2.Metric.SerializeToString,
            core__ingest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
