# snmpd.conf — mimics a Windows Server
agentAddress  udp:161
rocommunity   public default

sysObjectID   1.3.6.1.4.1.311.1.1.3.1.2

sysDescr      Hardware: Intel64 Family 6 Model 85 AT/AT COMPATIBLE - \
              Software: Windows Version 6.3 (Build 17763 Multiprocessor Free)
sysName       WIN-SERVER-SIM
sysContact    admin@company.com
sysLocation   DataCenter-Rack-B2