rocommunity public
sysLocation "Nexora Lab"
sysContact "admin@nexora.local"

agentAddress udp:0.0.0.0:161

view   all  included   .1
access notConfigGroup ""      any       noauth    exact  all    none   none