# snmpd.conf — mimics MikroTik RouterOS
agentAddress  udp:161
rocommunity   public default

# 1.3.6.1.4.1.14988 → matches "mikrotik" + "router"
sysObjectID   1.3.6.1.4.1.14988.1

sysDescr      RouterOS CCR1036-12G-4S (MIPSBE) version 6.49.6 (stable)
sysName       MikroTik-Router-SIM
sysContact    admin@company.com
sysLocation   DataCenter-Rack-C1